#!/usr/bin/env python3
"""Generate ds4_unicode_lmn.inc: sorted (start, end, class) ranges for the
Unicode general categories the qwen35 pre-tokenizer needs.

class 1 = L*  (letter)         -> regex \\p{L}
class 2 = M*  (mark)           -> regex \\p{M}
class 3 = N*  (number)         -> regex \\p{N}

Generated from Python's unicodedata (Unicode %s) so the table is
regenerable and auditable rather than hand-maintained.  ASCII is omitted: the
C side handles it inline for speed.
"""
import sys, unicodedata

CLS = {'L': 1, 'M': 2, 'N': 3}
MAX = 0x110000

ranges = []
start = None
cur = 0
for cp in range(128, MAX):
    cat = unicodedata.category(chr(cp))
    cls = CLS.get(cat[0], 0)
    if cls != cur:
        if cur:
            ranges.append((start, cp - 1, cur))
        start = cp if cls else None
        cur = cls
if cur:
    ranges.append((start, MAX - 1, cur))

# merge adjacent same-class ranges (a codepoint with no category change can
# still be split if unicodedata returns 'Cn' inconsistently); harmless if not.
with open('ds4_unicode_lmn.inc', 'w') as f:
    f.write("/* Generated by gen_lmn_table.py from Python unicodedata (Unicode %s).\n"
            " * Sorted, non-overlapping (first, last, class) ranges for the Unicode\n"
            " * categories the qwen35 pre-tokenizer matches: 1 = L*, 2 = M*, 3 = N*.\n"
            " * ASCII is excluded and handled inline by qwen35_ucat().  Do not edit by\n"
            " * hand; regenerate instead. */\n" % unicodedata.unidata_version)
    f.write("#define DS4_UNICODE_LMN_RANGES %d\n" % len(ranges))
    f.write("static const uint32_t ds4_unicode_lmn[DS4_UNICODE_LMN_RANGES][3] = {\n")
    for i in range(0, len(ranges), 4):
        chunk = ranges[i:i+4]
        f.write("    " + " ".join("{0x%05x,0x%05x,%d}," % r for r in chunk) + "\n")
    f.write("};\n")
print("ranges:", len(ranges))
